DROP TABLE HISTORICO CASCADE CONSTRAINTS;
DROP TABLE AVALIACAO CASCADE CONSTRAINTS;
DROP TABLE EPISODIO CASCADE CONSTRAINTS;
DROP TABLE TEMPORADA CASCADE CONSTRAINTS;
DROP TABLE CONTEUDO_ARTISTA CASCADE CONSTRAINTS;
DROP TABLE CONTEUDO_GENERO CASCADE CONSTRAINTS;
DROP TABLE CONTEUDO CASCADE CONSTRAINTS;
DROP TABLE ARTISTA CASCADE CONSTRAINTS;
DROP TABLE GENERO CASCADE CONSTRAINTS;
DROP TABLE ASSINATURA CASCADE CONSTRAINTS;
DROP TABLE PERFIL CASCADE CONSTRAINTS;
DROP TABLE USUARIO CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_USUARIO;
DROP SEQUENCE SEQ_PERFIL;
DROP SEQUENCE SEQ_ASSINATURA;
DROP SEQUENCE SEQ_CONTEUDO;
DROP SEQUENCE SEQ_GENERO;
DROP SEQUENCE SEQ_ARTISTA;
DROP SEQUENCE SEQ_TEMPORADA;
DROP SEQUENCE SEQ_EPISODIO;
DROP SEQUENCE SEQ_AVALIACAO;
DROP SEQUENCE SEQ_HISTORICO;

CREATE SEQUENCE SEQ_PERFIL START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ASSINATURA START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_USUARIO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_HISTORICO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_AVALIACAO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CONTEUDO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_GENERO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ARTISTA START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_TEMPORADA START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_EPISODIO START WITH 1 INCREMENT BY 1;

CREATE TABLE PERFIL(
    ID NUMBER PRIMARY KEY,
    RESTRICAO_IDADE NUMBER CHECK (RESTRICAO_IDADE >= 0),
    URL_IMG_AVATAR VARCHAR2(255),
    NOME VARCHAR2(100) NOT NULL,
    USUARIO_ID NUMBER NOT NULL, 
);

CREATE TABLE USUARIO(
    ID NUMBER PRIMARY KEY,
    DATA_CADASTRO DATE,
    DATA_NASCIMENTO DATE,
    SENHA VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(150) NOT NULL UNIQUE,
    NOME VARCHAR2(100) NOT NULL,
    ASSINATURA_ID NUMBER,
);

CREATE TABLE HISTORICO(
    ID NUMBER PRIMARY KEY,
    MINUTOS_ASSISTIDOS NUMBER,
    DATA_HORA DATE,
    PERFIL_ID NUMBER NOT NULL
    EPISODIO_ID NUMBER,
    CONTEUDO_ID NUMBER
);

CREATE TABLE ASSINATURA(
    ID NUMBER PRIMARY KEY,
    MAX_TELAS NUMBER, 
    MAX_RESOLUCAO NUMBER,
    PRECO_MENSAL NUMBER,
    NOME VARCHAR2(100),
);

CREATE TABLE AVALIACAO(
    ID NUMBER PRIMARY KEY,
    DATA DATE,
    COMENTARIO CLOB,
    NOTA NUMBER,
    PERFIL_ID NUMBER NOT NULL,
    CONTEUDO_ID NUMBER NOT NULL
);

CREATE TABLE CONTEUDO(
    ID NUMBER PRIMARY KEY,
    DURACAO_MINUTOS NUMBER,
    TIPO VARCHAR2(50),
    CLASSIFICACAO_INDICATIVA NUMBER CHECK (CLASSIFICACAO_INDICATIVA >= 0),
    ANO_LANCAMENTO NUMBER CHECK (ANO_LANCAMENTO >= 0),
    SINOPSE CLOB,
    TITULO VARCHAR2(200) NOT NULL
);

CREATE TABLE GENERO(
    ID NUMBER PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL
);

CREATE TABLE ARTISTA(
    ID NUMBER PRIMARY KEY,
    BIOGRAFIA CLOB,
    DATA_NASCIMENTO DATE,
    NOME VARCHAR2(100) NOT NULL
);

CREATE TABLE TEMPORADA(
    ID NUMBER PRIMARY KEY,
    NUMERO NUMBER,
    TITULO VARCHAR2(200),
    DATA_DE_LANCAMENTO DATE,
    CONTEUDO_ID NUMBER NOT NULL
);

CREATE TABLE EPISODIO(
    ID NUMBER PRIMARY KEY,
    NUMERO NUMBER,
    TITULO VARCHAR2(200),
    DESCRICAO CLOB,
    DURACAO_MINUTOS NUMBER,
    TEMPORADA_ID NUMBER NOT NULL
);

CREATE TABLE CONTEUDO_GENERO(
    CONTEUDO_ID NUMBER NOT NULL,
    GENERO_ID NUMBER NOT NULL,
    CONSTRAINT PK_CONTEUDO_GENERO PRIMARY KEY (CONTEUDO_ID, GENERO_ID)
);

CREATE TABLE CONTEUDO_ARTISTA(
    CONTEUDO_ID NUMBER NOT NULL,
    ARTISTA_ID NUMBER NOT NULL,
    FUNCAO VARCHAR2(100),
    CONSTRAINT PK_CONTEUDO_ARTISTA PRIMARY KEY (CONTEUDO_ID, ARTISTA_ID)
);

ALTER TABLE PERFIL
ADD CONSTRAINT FK_PERFIL_USUARIO
FOREIGN KEY (USUARIO_ID)
REFERENCES USUARIO(ID);

ALTER TABLE USUARIO
ADD CONSTRAINT FK_USUARIO_ASSINATURA
FOREIGN KEY (ASSINATURA_ID)
REFERENCES ASSINATURA(ID);

ALTER TABLE HISTORICO
ADD CONSTRAINT FK_HISTORICO_PERFIL
FOREIGN KEY (PERFIL_ID)
REFERENCES PERFIL(ID);

ALTER TABLE HISTORICO
ADD CONSTRAINT FK_HISTORICO_EPISODIO
FOREIGN KEY (EPISODIO_ID)
REFERENCES EPISODIO(ID);

ALTER TABLE HISTORICO
ADD CONSTRAINT FK_HISTORICO_CONTEUDO
FOREIGN KEY (CONTEUDO_ID)
REFERENCES CONTEUDO(ID);

ALTER TABLE AVALIACAO
ADD CONSTRAINT FK_AVALIACAO_PERFIL
FOREIGN KEY (PERFIL_ID)
REFERENCES PERFIL(ID);

ALTER TABLE AVALIACAO
ADD CONSTRAINT FK_AVALIACAO_CONTEUDO
FOREIGN KEY (CONTEUDO_ID)
REFERENCES CONTEUDO(ID);

ALTER TABLE AVALIACAO
ADD CONSTRAINT CK_AVALIACAO_NOTA
CHECK (NOTA BETWEEN 0 AND 5);

ALTER TABLE TEMPORADA
ADD CONSTRAINT FK_TEMPORADA_CONTEUDO
FOREIGN KEY (CONTEUDO_ID)
REFERENCES CONTEUDO(ID);

ALTER TABLE EPISODIO
ADD CONSTRAINT FK_EPISODIO_TEMPORADA
FOREIGN KEY (TEMPORADA_ID)
REFERENCES TEMPORADA(ID);

ALTER TABLE CONTEUDO_GENERO
ADD CONSTRAINT FK_CG_CONTEUDO
FOREIGN KEY (CONTEUDO_ID)
REFERENCES CONTEUDO(ID);

ALTER TABLE CONTEUDO_GENERO
ADD CONSTRAINT FK_CG_GENERO
FOREIGN KEY (GENERO_ID)
REFERENCES GENERO(ID);

ALTER TABLE CONTEUDO_ARTISTA
ADD CONSTRAINT FK_CA_CONTEUDO
FOREIGN KEY (CONTEUDO_ID)
REFERENCES CONTEUDO(ID);

ALTER TABLE CONTEUDO_ARTISTA
ADD CONSTRAINT FK_CA_ARTISTA
FOREIGN KEY (ARTISTA_ID)
REFERENCES ARTISTA(ID);
