-- ===============================================
-- LIMPEZA DO AMBIENTE (CASO OBJETOS EXISTAM)
-- ===============================================

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE AVALIACAO CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE HISTORICO CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE EPISODIO CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE TEMPORADA CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE CONTEUDO_ARTISTA CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE CONTEUDO_GENERO CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE PERFIL CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE USUARIO CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE CONTEUDO CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE ARTISTA CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE GENERO CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE ASSINATURA CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_HISTORICO';
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_AVALIACAO';
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_EPISODIO';
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TEMPORADA';
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PERFIL';
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_USUARIO';
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CONTEUDO';
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_ARTISTA';
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_GENERO';
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_ASSINATURA';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

-- ===============================================
-- SEQUENCES
-- ===============================================

CREATE SEQUENCE SEQ_ASSINATURA;
CREATE SEQUENCE SEQ_GENERO;
CREATE SEQUENCE SEQ_ARTISTA;
CREATE SEQUENCE SEQ_CONTEUDO;
CREATE SEQUENCE SEQ_USUARIO;
CREATE SEQUENCE SEQ_PERFIL;
CREATE SEQUENCE SEQ_TEMPORADA;
CREATE SEQUENCE SEQ_EPISODIO;
CREATE SEQUENCE SEQ_HISTORICO;
CREATE SEQUENCE SEQ_AVALIACAO;

-- ===============================================
-- TABELAS BASE
-- ===============================================

CREATE TABLE ASSINATURA (
    ID NUMBER PRIMARY KEY,
    NOME VARCHAR2(255) NOT NULL CHECK (UPPER(NOME) IN ('BASICO','PADRAO','PREMIUM')),
    PRECO_MENSAL NUMBER NOT NULL CHECK (PRECO_MENSAL > 0),
    MAX_RESOLUCAO VARCHAR2(10) NOT NULL CHECK (UPPER(MAX_RESOLUCAO) IN ('480P','720P','1080P','4K')),
    MAX_TELAS NUMBER NOT NULL CHECK (MAX_TELAS > 0)
);

CREATE TABLE GENERO (
    ID NUMBER PRIMARY KEY,
    NOME VARCHAR2(50) UNIQUE NOT NULL
);

CREATE TABLE ARTISTA (
    ID NUMBER PRIMARY KEY,
    NOME VARCHAR2(255) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    BIOGRAFIA VARCHAR2(255) NOT NULL
);

CREATE TABLE CONTEUDO (
    ID NUMBER PRIMARY KEY,
    TITULO VARCHAR2(150) NOT NULL,
    SINOPSE VARCHAR2(255) NOT NULL,
    ANO_LANCAMENTO NUMBER(4) NOT NULL,
    CLASSIFICACAO_INDICATIVA VARCHAR2(2) NOT NULL
        CHECK (UPPER(CLASSIFICACAO_INDICATIVA) IN ('L','6','10','12','14','16','18')),
    TIPO VARCHAR2(6) NOT NULL
        CHECK (UPPER(TIPO) IN ('FILME','SERIE')),
    DURACAO_MINUTOS NUMBER,
    CHECK (
        (UPPER(TIPO)='FILME' AND DURACAO_MINUTOS IS NOT NULL)
        OR
        (UPPER(TIPO)='SERIE' AND DURACAO_MINUTOS IS NULL)
    ),
    CHECK (DURACAO_MINUTOS IS NULL OR DURACAO_MINUTOS > 0)
);

-- ===============================================
-- TABELAS DEPENDENTES
-- ===============================================

CREATE TABLE USUARIO (
    ID NUMBER PRIMARY KEY,
    NOME VARCHAR2(255) NOT NULL,
    EMAIL VARCHAR2(150) UNIQUE NOT NULL,
    SENHA VARCHAR2(255) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    DATA_CADASTRO DATE NOT NULL,
    ID_ASSINATURA NUMBER NOT NULL,
    FOREIGN KEY (ID_ASSINATURA) REFERENCES ASSINATURA(ID),
    CHECK (DATA_NASCIMENTO < DATA_CADASTRO)
);

CREATE TABLE PERFIL (
    ID NUMBER PRIMARY KEY,
    NOME VARCHAR2(255) NOT NULL,
    URL_IMG_AVATAR VARCHAR2(255),
    RESTRICAO_IDADE VARCHAR2(2) DEFAULT 'L' NOT NULL
        CHECK (UPPER(RESTRICAO_IDADE) IN ('L','6','10','12','14','16','18')),
    ID_USUARIO NUMBER NOT NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID)
);

CREATE TABLE CONTEUDO_GENERO (
    ID_CONTEUDO NUMBER NOT NULL,
    ID_GENERO NUMBER NOT NULL,
    PRIMARY KEY (ID_CONTEUDO, ID_GENERO),
    FOREIGN KEY (ID_CONTEUDO) REFERENCES CONTEUDO(ID),
    FOREIGN KEY (ID_GENERO) REFERENCES GENERO(ID)
);

CREATE TABLE CONTEUDO_ARTISTA (
    ID_CONTEUDO NUMBER NOT NULL,
    ID_ARTISTA NUMBER NOT NULL,
    FUNCAO VARCHAR2(150) NOT NULL,
    PRIMARY KEY (ID_CONTEUDO, ID_ARTISTA),
    FOREIGN KEY (ID_CONTEUDO) REFERENCES CONTEUDO(ID),
    FOREIGN KEY (ID_ARTISTA) REFERENCES ARTISTA(ID)
);

CREATE TABLE TEMPORADA (
    ID NUMBER PRIMARY KEY,
    NUMERO NUMBER NOT NULL CHECK (NUMERO > 0),
    TITULO VARCHAR2(255) NOT NULL,
    DATA_LANCAMENTO DATE NOT NULL,
    ID_CONTEUDO NUMBER NOT NULL,
    FOREIGN KEY (ID_CONTEUDO) REFERENCES CONTEUDO(ID),
    UNIQUE (ID_CONTEUDO, NUMERO)
);

CREATE TABLE EPISODIO (
    ID NUMBER PRIMARY KEY,
    NUMERO NUMBER NOT NULL CHECK (NUMERO > 0),
    TITULO VARCHAR2(255) NOT NULL,
    DURACAO_MINUTOS NUMBER NOT NULL CHECK (DURACAO_MINUTOS > 0),
    DESCRICAO VARCHAR2(255) NOT NULL,
    ID_TEMPORADA NUMBER NOT NULL,
    FOREIGN KEY (ID_TEMPORADA) REFERENCES TEMPORADA(ID),
    UNIQUE (ID_TEMPORADA, NUMERO)
);

CREATE TABLE HISTORICO (
    ID NUMBER PRIMARY KEY,
    DATA_HORA TIMESTAMP NOT NULL,
    MINUTOS_ASSISTIDOS NUMBER NOT NULL CHECK (MINUTOS_ASSISTIDOS > 0),
    ID_EPISODIO NUMBER,
    ID_CONTEUDO NUMBER,
    ID_PERFIL NUMBER NOT NULL,
    FOREIGN KEY (ID_PERFIL) REFERENCES PERFIL(ID),
    FOREIGN KEY (ID_EPISODIO) REFERENCES EPISODIO(ID),
    FOREIGN KEY (ID_CONTEUDO) REFERENCES CONTEUDO(ID),
    CHECK (
        (ID_EPISODIO IS NULL AND ID_CONTEUDO IS NOT NULL)
        OR
        (ID_EPISODIO IS NOT NULL AND ID_CONTEUDO IS NULL)
    )
);

CREATE TABLE AVALIACAO (
    ID NUMBER PRIMARY KEY,
    NOTA NUMBER NOT NULL CHECK (NOTA BETWEEN 1 AND 5),
    COMENTARIO VARCHAR2(255),
    DATA DATE NOT NULL,
    ID_PERFIL NUMBER NOT NULL,
    ID_CONTEUDO NUMBER NOT NULL,
    FOREIGN KEY (ID_PERFIL) REFERENCES PERFIL(ID),
    FOREIGN KEY (ID_CONTEUDO) REFERENCES CONTEUDO(ID),
    UNIQUE (ID_PERFIL, ID_CONTEUDO)
);
