-- =====================================================
-- CRIAÇÃO DAS SEQUENCES PARA GERAÇÃO DE CHAVES PRIMÁRIAS
-- =====================================================

CREATE SEQUENCE SEQ_CONTEUDO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_GENERO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ARTISTA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_TEMPORADA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_EPISODIO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PERFIL START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_USUARIO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ASSINATURA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_AVALIACAO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_HISTORICO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- =====================================================
-- CRIAÇÃO DAS TABLES
-- =====================================================

CREATE TABLE ASSINATURA (
    ID NUMBER PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    PRECO_MENSAL NUMBER NOT NULL, 
    MAX_RESOLUCAO VARCHAR(10) NOT NULL,
    MAX_TELAS NUMBER NOT NULL,
    CONSTRAINT CK_ASSINATURA_NOME
        CHECK (UPPER(NOME) IN ('BASICO', 'PADRAO', 'PREMIUM')),
	CONSTRAINT CK_ASSINATURA_PRECO_POSITIVO
        CHECK (PRECO_MENSAL > 0),
    CONSTRAINT CK_ASSINATURA_RESOLUCAO
        CHECK (UPPER(MAX_RESOLUCAO) IN ('480P', '720P', '1080P', '4K')),
	CONSTRAINT CK_ASSINATURA_MAX_TELAS_POSITIVO
        CHECK (MAX_TELAS > 0)
);

CREATE TABLE GENERO (
    ID NUMBER PRIMARY KEY,
    NOME VARCHAR(50) UNIQUE NOT NULL 
);

CREATE TABLE ARTISTA (
    ID NUMBER PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    BIOGRAFIA VARCHAR(255) NOT NULL
);

CREATE TABLE CONTEUDO (
    ID NUMBER PRIMARY KEY,
    TITULO VARCHAR(150) NOT NULL,
    SINOPSE VARCHAR(255) NOT NULL,
    ANO_LANCAMENTO NUMBER(4) NOT NULL,
    CLASSIFICACAO_INDICATIVA VARCHAR(2) NOT NULL,
    TIPO VARCHAR(6) NOT NULL,
    DURACAO_MINUTOS NUMBER,
    CONSTRAINT CK_CONTEUDO_TIPO_DOMINIO
    	CHECK (UPPER(TIPO) IN ('FILME', 'SERIE')),
    CONSTRAINT CK_CONTEUDO_TIPO_DURACAO CHECK (
        (UPPER(TIPO) = 'FILME' AND DURACAO_MINUTOS IS NOT NULL)
        OR
        (UPPER(TIPO) = 'SERIE' AND DURACAO_MINUTOS IS NULL)
    ),
    CONSTRAINT CK_CONTEUDO_DURACAO_MINUTOS_POSITIVA 
    	CHECK (DURACAO_MINUTOS > 0),
    CONSTRAINT CK_CONTEUDO_CLASSIFICACAO_INDICATIVA
    	CHECK (UPPER(CLASSIFICACAO_INDICATIVA) IN ('L', '6', '10', '12', '14', '16', '18'))
);

CREATE TABLE USUARIO (
    ID NUMBER PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(150) NOT NULL UNIQUE,
    SENHA VARCHAR(255) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    DATA_CADASTRO DATE NOT NULL,
    ID_ASSINATURA NUMBER NOT NULL,
    CONSTRAINT FK_USUARIO_ASSINATURA FOREIGN KEY (ID_ASSINATURA)
        REFERENCES ASSINATURA (ID),
    CONSTRAINT CK_USUARIO_NASCIMENTO_ANTES_CADASTRO 
    	CHECK (DATA_NASCIMENTO < DATA_CADASTRO)
);

CREATE TABLE PERFIL (
    ID NUMBER PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    URL_IMG_AVATAR VARCHAR(255),
    RESTRICAO_IDADE VARCHAR(2) DEFAULT 'L' NOT NULL,
    ID_USUARIO NUMBER NOT NULL,
    CONSTRAINT FK_PERFIL_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES USUARIO (ID),
    CONSTRAINT CK_PERFIL_RESTRICAO_IDADE
        CHECK (UPPER(RESTRICAO_IDADE) IN ('L', '6', '10', '12', '14', '16', '18')),
   	CONSTRAINT UQ_PERFIL_NOME_USUARIO
    	UNIQUE (ID_USUARIO, NOME)
);

CREATE TABLE CONTEUDO_GENERO (
    ID_CONTEUDO NUMBER NOT NULL,
    ID_GENERO NUMBER NOT NULL,
    CONSTRAINT PK_CONTEUDO_GENERO PRIMARY KEY (ID_CONTEUDO, ID_GENERO),
    CONSTRAINT FK_CONTEUDO_GENERO_CONTEUDO FOREIGN KEY (ID_CONTEUDO)
        REFERENCES CONTEUDO (ID),
    CONSTRAINT FK_CONTEUDO_GENERO_GENERO FOREIGN KEY (ID_GENERO)
        REFERENCES GENERO (ID)
);

CREATE TABLE CONTEUDO_ARTISTA (
    ID_CONTEUDO NUMBER NOT NULL,
    ID_ARTISTA NUMBER NOT NULL,
    FUNCAO VARCHAR(150) NOT NULL,
    CONSTRAINT PK_CONTEUDO_ARTISTA PRIMARY KEY (ID_CONTEUDO, ID_ARTISTA),
    CONSTRAINT FK_CONTEUDO_ARTISTA_CONTEUDO FOREIGN KEY (ID_CONTEUDO)
        REFERENCES CONTEUDO (ID),
    CONSTRAINT FK_CONTEUDO_ARTISTA_ARTISTA FOREIGN KEY (ID_ARTISTA)
        REFERENCES ARTISTA (ID)
);

CREATE TABLE TEMPORADA (
    ID NUMBER PRIMARY KEY,
    NUMERO NUMBER NOT NULL,
    TITULO VARCHAR(255) NOT NULL,
    DATA_LANCAMENTO DATE NOT NULL,
    ID_CONTEUDO NUMBER NOT NULL,
    CONSTRAINT FK_TEMPORADA_CONTEUDO FOREIGN KEY (ID_CONTEUDO)
        REFERENCES CONTEUDO (ID),
    CONSTRAINT CK_TEMPORADA_NUMERO_POSITIVO
    	CHECK (NUMERO > 0),
    CONSTRAINT UQ_TEMPORADA_NUMERO_CONTEUDO
    	UNIQUE (ID_CONTEUDO, NUMERO)
);

CREATE TABLE EPISODIO (
    ID NUMBER PRIMARY KEY,
    NUMERO NUMBER NOT NULL,
    TITULO VARCHAR(255) NOT NULL,
    DURACAO_MINUTOS NUMBER NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL,
    ID_TEMPORADA NUMBER NOT NULL,
    
    CONSTRAINT FK_EPISODIO_TEMPORADA FOREIGN KEY (ID_TEMPORADA)
    	REFERENCES TEMPORADA (ID),
    CONSTRAINT CK_EPISODIO_DURACAO_MINUTOS_POSITIVA 
    	CHECK (DURACAO_MINUTOS > 0),
   	CONSTRAINT CK_EPISODIO_NUMERO_POSITIVO
    	CHECK (NUMERO > 0)
);

CREATE TABLE HISTORICO (
    ID NUMBER PRIMARY KEY,
    DATA_HORA TIMESTAMP NOT NULL,
    MINUTOS_ASSISTIDOS NUMBER NOT NULL,
    ID_EPISODIO NUMBER NULL,
    ID_CONTEUDO NUMBER NULL,
    ID_PERFIL NUMBER NOT NULL,
    CONSTRAINT FK_HISTORICO_PERFIL FOREIGN KEY (ID_PERFIL)
        REFERENCES PERFIL (ID),
    CONSTRAINT FK_HISTORICO_EPISODIO FOREIGN KEY (ID_EPISODIO)
        REFERENCES EPISODIO (ID),
    CONSTRAINT FK_HISTORICO_CONTEUDO FOREIGN KEY (ID_CONTEUDO)
        REFERENCES CONTEUDO (ID),
    CONSTRAINT CK_HISTORICO_EPISODIO_OU_CONTEUDO  CHECK (
        (ID_EPISODIO IS NULL AND ID_CONTEUDO IS NOT NULL)
        OR
        (ID_EPISODIO IS NOT NULL AND ID_CONTEUDO IS NULL)
    ),
    CONSTRAINT CK_HISTORICO_MINUTOS_ASSISTIDOS_POSITIVO 
    	CHECK (MINUTOS_ASSISTIDOS > 0)
);

CREATE TABLE AVALIACAO (
    ID NUMBER PRIMARY KEY,
    NOTA NUMBER NOT NULL,
    COMENTARIO VARCHAR(255),
    DATA DATE NOT NULL,
    ID_PERFIL NUMBER NOT NULL,
    ID_CONTEUDO NUMBER NOT NULL,
    CONSTRAINT FK_AVALIACAO_PERFIL FOREIGN KEY (ID_PERFIL)
        REFERENCES PERFIL (ID),
    CONSTRAINT FK_AVALIACAO_CONTEUDO FOREIGN KEY (ID_CONTEUDO)
        REFERENCES CONTEUDO (ID),
    CONSTRAINT CK_AVALIACAO_NOTA_VALIDA
    	CHECK (NOTA IN (1, 2, 3, 4, 5)),
    CONSTRAINT UQ_AVALIACAO_PERFIL_CONTEUDO
    	UNIQUE (ID_PERFIL, ID_CONTEUDO)
);

-- =====================================================
-- DROP DE CONSTRAINTS - FOREIGN KEYS
-- =====================================================

ALTER TABLE AVALIACAO DROP CONSTRAINT FK_AVALIACAO_PERFIL;
ALTER TABLE AVALIACAO DROP CONSTRAINT FK_AVALIACAO_CONTEUDO;
ALTER TABLE HISTORICO DROP CONSTRAINT FK_HISTORICO_PERFIL;
ALTER TABLE HISTORICO DROP CONSTRAINT FK_HISTORICO_EPISODIO;
ALTER TABLE HISTORICO DROP CONSTRAINT FK_HISTORICO_CONTEUDO;
ALTER TABLE EPISODIO DROP CONSTRAINT FK_EPISODIO_TEMPORADA;
ALTER TABLE TEMPORADA DROP CONSTRAINT FK_TEMPORADA_CONTEUDO;
ALTER TABLE CONTEUDO_ARTISTA DROP CONSTRAINT FK_CONTEUDO_ARTISTA_CONTEUDO;
ALTER TABLE CONTEUDO_ARTISTA DROP CONSTRAINT FK_CONTEUDO_ARTISTA_ARTISTA;
ALTER TABLE CONTEUDO_GENERO DROP CONSTRAINT FK_CONTEUDO_GENERO_CONTEUDO;
ALTER TABLE CONTEUDO_GENERO DROP CONSTRAINT FK_CONTEUDO_GENERO_GENERO;
ALTER TABLE PERFIL DROP CONSTRAINT FK_PERFIL_USUARIO;
ALTER TABLE USUARIO DROP CONSTRAINT FK_USUARIO_ASSINATURA;

-- =====================================================
-- DROP DE CONSTRAINTS - UNIQUE
-- =====================================================

ALTER TABLE AVALIACAO DROP CONSTRAINT UQ_AVALIACAO_PERFIL_CONTEUDO;
ALTER TABLE TEMPORADA DROP CONSTRAINT UQ_TEMPORADA_NUMERO_CONTEUDO;
ALTER TABLE PERFIL DROP CONSTRAINT UQ_PERFIL_NOME_USUARIO;

-- =====================================================
-- DROP DE CONSTRAINTS - CHECK
-- =====================================================

ALTER TABLE AVALIACAO DROP CONSTRAINT CK_AVALIACAO_NOTA_VALIDA;
ALTER TABLE HISTORICO DROP CONSTRAINT CK_HISTORICO_EPISODIO_OU_CONTEUDO;
ALTER TABLE HISTORICO DROP CONSTRAINT CK_HISTORICO_MINUTOS_ASSISTIDOS_POSITIVO;
ALTER TABLE EPISODIO DROP CONSTRAINT CK_EPISODIO_DURACAO_MINUTOS_POSITIVA;
ALTER TABLE EPISODIO DROP CONSTRAINT CK_EPISODIO_NUMERO_POSITIVO;
ALTER TABLE TEMPORADA DROP CONSTRAINT CK_TEMPORADA_NUMERO_POSITIVO;
ALTER TABLE PERFIL DROP CONSTRAINT CK_PERFIL_RESTRICAO_IDADE;
ALTER TABLE USUARIO DROP CONSTRAINT CK_USUARIO_NASCIMENTO_ANTES_CADASTRO;
ALTER TABLE CONTEUDO DROP CONSTRAINT CK_CONTEUDO_TIPO_DOMINIO;
ALTER TABLE CONTEUDO DROP CONSTRAINT CK_CONTEUDO_TIPO_DURACAO;
ALTER TABLE CONTEUDO DROP CONSTRAINT CK_CONTEUDO_DURACAO_MINUTOS_POSITIVA;
ALTER TABLE CONTEUDO DROP CONSTRAINT CK_CONTEUDO_CLASSIFICACAO_INDICATIVA;
ALTER TABLE ASSINATURA DROP CONSTRAINT CK_ASSINATURA_NOME;
ALTER TABLE ASSINATURA DROP CONSTRAINT CK_ASSINATURA_PRECO_POSITIVO;
ALTER TABLE ASSINATURA DROP CONSTRAINT CK_ASSINATURA_RESOLUCAO;
ALTER TABLE ASSINATURA DROP CONSTRAINT CK_ASSINATURA_MAX_TELAS_POSITIVO;

-- =====================================================
-- DROP DE CONSTRAINTS - PRIMARY KEYS
-- =====================================================

ALTER TABLE AVALIACAO DROP PRIMARY KEY;
ALTER TABLE HISTORICO DROP PRIMARY KEY;
ALTER TABLE EPISODIO DROP PRIMARY KEY;
ALTER TABLE TEMPORADA DROP PRIMARY KEY;
ALTER TABLE CONTEUDO_ARTISTA DROP PRIMARY KEY;
ALTER TABLE CONTEUDO_GENERO DROP PRIMARY KEY;
ALTER TABLE PERFIL DROP PRIMARY KEY;
ALTER TABLE USUARIO DROP PRIMARY KEY;
ALTER TABLE CONTEUDO DROP PRIMARY KEY;
ALTER TABLE ARTISTA DROP PRIMARY KEY;
ALTER TABLE GENERO DROP PRIMARY KEY;
ALTER TABLE ASSINATURA DROP PRIMARY KEY;

-- =====================================================
-- DROP DE SEQUENCES
-- =====================================================

DROP SEQUENCE SEQ_HISTORICO;
DROP SEQUENCE SEQ_AVALIACAO;
DROP SEQUENCE SEQ_EPISODIO;
DROP SEQUENCE SEQ_TEMPORADA;
DROP SEQUENCE SEQ_PERFIL;
DROP SEQUENCE SEQ_USUARIO;
DROP SEQUENCE SEQ_CONTEUDO;
DROP SEQUENCE SEQ_ARTISTA;
DROP SEQUENCE SEQ_GENERO;
DROP SEQUENCE SEQ_ASSINATURA;

-- =====================================================
-- DROP DE TABLES
-- =====================================================

DROP TABLE AVALIACAO;
DROP TABLE HISTORICO;
DROP TABLE EPISODIO;
DROP TABLE TEMPORADA;
DROP TABLE CONTEUDO_ARTISTA;
DROP TABLE CONTEUDO_GENERO;
DROP TABLE PERFIL;
DROP TABLE USUARIO;
DROP TABLE CONTEUDO;
DROP TABLE ARTISTA;
DROP TABLE GENERO;
DROP TABLE ASSINATURA;