CREATE OR REPLACE PROCEDURE SP_MESCLAR_PERFIS(P_ID_PERFIL_ORIGEM NUMBER, P_ID_PERFIL_DESTINO NUMBER) 
IS
BEGIN
  IF P_ID_PERFIL_ORIGEM IS NULL OR P_ID_PERFIL_DESTINO IS NULL 
    THEN RETURN;
  END IF; 
  IF P_ID_PERFIL_ORIGEM = P_ID_PERFIL_DESTINO 
    THEN RETURN;
  END IF;
  
  UPDATE HISTORICO
  SET id_perfil = P_ID_PERFIL_DESTINO
  WHERE id_perfil = P_ID_PERFIL_ORIGEM;
  
  UPDATE Avaliacao
  SET id_perfil = P_ID_PERFIL_DESTINO
  WHERE id_perfil = P_ID_PERFIL_ORIGEM;
  
  DELETE FROM Perfil
  WHERE id = P_ID_PERFIL_ORIGEM;
  COMMIT; 

END;
